# services:
#   prometheus:
#     image: prom/prometheus:v3.1.0
#     ports:
#       - "9090:9090"
#     volumes:
#       - ./configs/prometheus-config.yml:/etc/prometheus/prometheus.yml
#       - prometheus-data:/prometheus
#     command:
#       - "--config.file=/etc/prometheus/prometheus.yml"
#     restart: always
#     networks:
#       - monitoring
#     extra_hosts:
#       - "host.docker.internal:host-gateway"
#
#   mimir:
#     image: grafana/mimir:2.14.3
#     ports:
#       - "9009:9009"
#       - "9095:9095"
#     volumes:
#       - ./configs/mimir-config.yml:/etc/mimir/mimir.yml
#       - mimir-data:/mimir
#     command:
#       - "-config.file=/etc/mimir/mimir.yml"
#     restart: always
#     networks:
#       - monitoring
#
#   promtail:
#     image: grafana/promtail:3.4
#     volumes:
#       - /var/log/journal:/var/log/journal:ro
#       - promtail-data:/promtail
#       - ./configs/promtail-config.yml:/etc/promtail/config.yml
#     command: -config.file=/etc/promtail/config.yml
#     restart: always
#     networks:
#       - monitoring
#
#   loki:
#     image: grafana/loki:3.4
#     ports:
#       - "3100:3100"
#     volumes:
#       - loki-data:/loki
#       - ./configs/loki-config.yml:/etc/loki/local-config.yml
#     command: -config.file=/etc/loki/local-config.yml
#     restart: always
#     networks:
#       - monitoring
#
#   grafana:
#     image: grafana/grafana:11.5.1
#     ports:
#       - "3001:3000"
#     env_file:
#       - .env.production
#     volumes:
#       - ./configs/provisioning:/etc/grafana/provisioning
#       - grafana-data:/var/lib/grafana
#     restart: always
#     networks:
#       - monitoring
#
# volumes:
#   prometheus-data:
#   mimir-data:
#   promtail-data:
#   loki-data:
#   grafana-data:
#
# networks:
#   monitoring:
#     driver: bridge
#

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - speedcubingslovakia

networks:
  speedcubingslovakia:
