services:
  prometheus:
    image: prom/prometheus:3.1.0
    ports:
      - "9090:9090"
    volumes:
      - ./configs/prometheus-config.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    restart: always
    networks:
      - monitoring

  mimir:
    image: grafana/mimir:2.14.3
    ports:
      - "9009:9009"
      - "9095:9095"
    volumes:
      - ./configs/mimir-config.yml:/etc/mimir/mimir.yml
      - mimir-data:/mimir
    command:
      - "-config.file=/etc/mimir/mimir.yml"
    restart: always
    networks:
      - monitoring

  promtail:
    image: grafana/promtail:latest
    volumes:
      - /var/log/journal/backend:/var/log/journal/backend:ro
      - promtail-positions:/tmp
      - ./configs/promtail-config.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    restart: always
    networks:
      - monitoring

  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    volumes:
      - loki-data:/loki
      - ./configs/loki-config.yml:/etc/loki/local-config.yml
    command: -config.file=/etc/loki/local-config.yml
    restart: always
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3001:3000"
    env_file:
      - .env.production
    volumes:
      - ./configs/provisioning:/etc/grafana/provisioning
      - grafana-data:/var/lib/grafana
    restart: always
    networks:
      - monitoring

  volumes:
    prometheus-data:
    mimir-data:
    promtail-positions:
    loki-data:
    grafana-data:

networks:
  monitoring:
    driver: bridge
