server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: backend
    backend:
      path: /var/log/journal
      labels:
        job: backend
        service: backend
    relabel_configs:
      - source_labels: ["__journal__systemd_unit"]
        target_label: "unit"
    pipeline_stages:
      - regex:
          expression: "^[^{]*(?P<json>{.*})"
      - json:
          expressions:
            time: time
            level: level
            msg: msg
            method: method
            path: path
            status: status
            client_ip: client_ip
            latency: latency
            user_agent: user_agent
      - labels:
          level:
          method:
          path:
          status:
