global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "alloy"
    static_configs:
      - targets: ["grafana-alloy:12345"]

  - job_name: "backend"
    static_configs:
      - targets: ["backend:8000"]

  - job_name: "loki"
    static_configs:
      - targets: ["loki:3100"]
