BEGIN;

CREATE TABLE IF NOT EXISTS tags (
  tag_id BIGSERIAL PRIMARY KEY,
  label TEXT NOT NULL,
  color TEXT NOT NULL,
  timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT tags_unique UNIQUE(label, color) 
);

COMMIT;
