apiVersion: 1
datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://mimir:9009/prometheus
    uid: prometheus-ds-001
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
