global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "speedcubingslovakia-backend"
    static_configs:
      - targets: ["host.docker.internal/api"]

remote_write:
  - url: "http://mimir:9009/api/v1/push"
    remote_timeout: 30s
