{
 "title": "Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   { "name": "prometheus", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Success requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{code!~\"4..|5..\"}[5m])) OR vector(0)",
     "legendFormat": "# requests / sec over last 5 min"
    }
   ]
  },
  {
   "title": "Error requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{code=~\"4..|5..\"}[5m])) OR vector(0)",
     "legendFormat": "# requests / sec over last 5 min"
    }
   ]
  },
  {
   "title": "Success requests to total rate per sec over last 5 min",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (\n  (sum(rate(http_requests_total{code!~\"4..|5..\"}[5m])) OR vector(0)) / sum(rate(http_requests_total[5m]))\n) or 100 * (sum(rate(http_requests_total[5m])) == 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU usage per sec over last 5 min",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * rate(process_cpu_seconds_total[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by (level) ( count_over_time({job=\"go-todo-app\"} | json | level!=\"\"[1m]) )",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Request duration percentiles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by (le) (http_request_duration_seconds_bucket))",
     "legendFormat": "50th percentile"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (le) (http_request_duration_seconds_bucket))",
     "legendFormat": "90th percentile"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le) (http_request_duration_seconds_bucket))",
     "legendFormat": "99th percentile"
    }
   ]
  }
 ]
}