name: Build and Push 

on:
  push:
    branches:
      - main

jobs:
  metadata:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.meta.outputs.version }}
      labels: ${{ steps.meta.outputs.labels }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/${{ github.repository }}/nginx
            ghcr.io/${{ github.repository }}/backend
            ghcr.io/${{ github.repository }}/cron
            ghcr.io/${{ github.repository }}/scrambling
          tags: |
            type=sha

  build-nginx:
    runs-on: ubuntu-latest
    needs: metadata
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v4
        with:
          context: .
          file: docker/production/nginx.Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}/nginx:${{ needs.metadata.outputs.image_tag }}
          labels: ${{ needs.metadata.outputs.labels }}

  build-backend:
    runs-on: ubuntu-latest
    needs: metadata
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v4
        with:
          context: ./backend
          file: docker/production/backend.Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}/backend:${{ needs.metadata.outputs.image_tag }}
          labels: ${{ needs.metadata.outputs.labels }}

  build-cron:
    runs-on: ubuntu-latest
    needs: metadata
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v4
        with:
          context: ./backend
          file: docker/production/cron.Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}/cron:${{ needs.metadata.outputs.image_tag }}
          labels: ${{ needs.metadata.outputs.labels }}

  build-scrambling:
    runs-on: ubuntu-latest
    needs: metadata
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v4
        with:
          context: ./scrambling
          file: docker/production/scrambling.Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}/scrambling:${{ needs.metadata.outputs.image_tag }}
          labels: ${{ needs.metadata.outputs.labels }}

  update-docker-compose:
    runs-on: ubuntu-latest
    needs: [build-nginx, build-backend, build-cron, build-scrambling]
    steps:
      - uses: actions/checkout@v3
      - uses: mikefarah/yq@v4.27.5
        with:
          cmd: |
            yq e '.services.nginx.image = "ghcr.io/${{ github.repository }}/nginx:${{ needs.metadata.outputs.image_tag }}"' -i docker-compose.prod.yml &&
            yq e '.services.backend.image = "ghcr.io/${{ github.repository }}/backend:${{ needs.metadata.outputs.image_tag }}"' -i docker-compose.prod.yml &&
            yq e '.services.cron.image = "ghcr.io/${{ github.repository }}/cron:${{ needs.metadata.outputs.image_tag }}"' -i docker-compose.prod.yml &&
            yq e '.services.scrambling.image = "ghcr.io/${{ github.repository }}/scrambling:${{ needs.metadata.outputs.image_tag }}"' -i docker-compose.prod.yml
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update docker-compose.prod.yml with new image tags"
          branch: main
          file_pattern: docker-compose.prod.yml
