name: Deploy to server
on: [push]

jobs:
  Deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Pull latest code
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            cd ${{ secrets.WORKDIR }}
            git pull

      - name: Rebuild and restart backend
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            cd ${{ secrets.WORKDIR }}/backend/main
            go build main.go
            sudo systemctl daemon-reload

      - name: Rebuild and restart frontend
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            cd ${{ secrets.WORKDIR }}/frontend
            rm -rf build
            npm run build
            rm -rf ${{ secrets.FRONTEND_DEPLOY_DIR }}
            mv ./build ${{ secrets.FRONTEND_DEPLOY_DIR }}
            sudo service nginx reload
