name: PR Tests

on:
  pull_request:
    branches:
      - main

jobs:
  frontend-tests:
    uses: ./.github/workflows/frontend_tests.yml
  backend-tests:
    uses: ./.github/workflows/backend_tests.yml
